# Melinda node tests

name: Melinda-node-tests

on: push

jobs:
  build-node-versions:
    name: Node version matrix
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Helsinki

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        NPM_CONFIG_IGNORE_SCRIPTS: true
        MONGOMS_DOWNLOAD_URL: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel80-7.0.12.tgz
        MONGOMS_VERSION: 7.0.12
    - run: npm i -g npm@latest
    - run: npm audit --package-lock-only --production --audit-level=high
    - run: npm i
    - run: npm test
    - run: npm run build --if-present

  njsscan:
    name: Njsscan-check
    runs-on: ubuntu-latest
    container: node:18

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'

  license-scan:
    name: License compliance check
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - uses: actions/checkout@v4
      - uses: mikaelvesavuori/license-compliance-action@v1
        with:
          exclude_pattern: /^@natlibfi/

  publish:
    name: Npm publishing
    runs-on: ubuntu-latest
    container: node:18
    needs: [build-node-versions, njsscan]
    if: contains(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MELINDA_RECORD_IMPORT_COMMONS_JS_NPM_TOKEN }}